// export default {
//     PlusJakartaSans_Bold: "PlusJakartaSans-Bold",
//     PlusJakartaSans_BoldItalic: "PlusJakartaSans-BoldItalic",
//     PlusJakartaSans_ExtraBold: "PlusJakartaSans-ExtraBold",
//     PlusJakartaSans_ExtraBoldItalic: "PlusJakartaSans-ExtraBoldItalic",
//     PlusJakartaSans_ExtraLight: "PlusJakartaSans-ExtraLight",
//     PlusJakartaSans_ExtraLightItalic: "PlusJakartaSans-ExtraLightItalic",
//     PlusJakartaSans_Italic: "PlusJakartaSans-Italic",
//     PlusJakartaSans_Light: "PlusJakartaSans-Light",
//     PlusJakartaSans_LightItalic: "PlusJakartaSans-LightItalic",
//     PlusJakartaSans_Medium: "PlusJakartaSans-Medium",
//     PlusJakartaSans_MediumItalic: "PlusJakartaSans-MediumItalic",
//     PlusJakartaSans_Regular: "PlusJakartaSans-Regular",
//     PlusJakartaSans_SemiBold: "PlusJakartaSans-SemiBold",
//     PlusJakartaSans_SemiBoldItalic: "PlusJakartaSans-SemiBoldItalic",
//     //   POPPINS_BLACK: 'Poppins-Black',
//     POPPINS_BLACK: "Poppins-Black",
//     POPPINS_BOLD: "Poppins-Bold",
//     POPPINS_EXTRA_BOLD: "Poppins-ExtraBold",
//     POPPINS_EXTRA_LIGHT: "Poppins-ExtraLight",
//     POPPINS_LIGHT: "Poppins-Light",
//     POPPINS_MEDIUM: "Poppins-Medium",
//     POPPINS_REGULAR: "Poppins-Regular",
//     POPPINS_SEMI_BOLD: "Poppins-SemiBold",
//     POPPINS_THIN: "Poppins-Thin",
//   };
