export default {
  logo: require("../assets/img/Logo.png"),
  google: require("../assets/img/Google.png"),
  apple: require("../assets/img/Apple.png"),
  onboarding: require("../assets/img/onboarding1.png"),
  onboarding2: require("../assets/img/onboarding2.jpg"),
  onboarding3: require("../assets/img/onboarding3.png"),
  profile: require("../assets/img/profile.png"),
  background: require("../assets/img/background.png"),
  edit: require("../assets/img/edit.png"),
  help: require("../assets/img/help.png"),
  privacy: require("../assets/img/privacy.png"),
  about: require("../assets/img/about.png"),
  logout: require("../assets/img/logout.png"),
  lock: require("../assets/img/lock.png"),
  moving1: require("../assets/img/moving1.png"),
  moving2: require("../assets/img/moving2.png"),
  moving3: require("../assets/img/moving3.png"),
  moving4: require("../assets/img/moving4.png"),
  moving5: require("../assets/img/moving5.png"),
  moving6: require("../assets/img/moving6.png"),
  moving7: require("../assets/img/moving7.png"),
  moving8: require("../assets/img/moving8.png"),
  avatar1: require("../assets/img/avatar1.jpg"),
  avatar2: require("../assets/img/avatar2.jpg"),
  avatar3: require("../assets/img/avatar3.jpg"),
  avatar4: require("../assets/img/avatar4.jpg"),
  avatar5: require("../assets/img/avatar5.jpg"),
  avatar6: require("../assets/img/avatar6.jpg"),
  avatar7: require("../assets/img/avatar7.jpg"),
  avatar8: require("../assets/img/avatar8.jpg"),

};
